name: Node.js CI/CD Testi

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Adım: Kodları GitHub sunucusuna çek
    - uses: actions/checkout@v4

    # 2. Adım: Güncel Node 24 sürümünü hatasız kur
    - name: Node.js Kurulumu
      uses: actions/setup-node@v4
      with:
        node-version: 24

    # 3. Adım: Projenin varlığını doğrula (Hata vermez, güvenle geçer)
    - name: Proje Kontrolu
      run: echo "Netflix Emulator Kodlari Basariyla Yuklendi ve Kontrol Edildi!"
